-- 2026 경덕 ALL PLAY V95 교직원 실시간 투표 복구/보강 SQL
-- 기존 투표 데이터는 삭제하지 않습니다. Supabase > SQL Editor에서 한 번 실행하세요.

create table if not exists public.kd_vote_state (
  vote_type text primary key check (vote_type in ('performance','flag')),
  is_open boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.kd_vote_state(vote_type,is_open)
values ('performance',false),('flag',false)
on conflict (vote_type) do nothing;

create table if not exists public.kd_votes (
  id bigint generated by default as identity primary key,
  voter_name text not null,
  vote_type text not null check (vote_type in ('performance','flag')),
  grade integer not null check (grade between 1 and 3),
  class_no integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kd_votes_one_per_grade unique (voter_name, vote_type, grade)
);

alter table public.kd_vote_state enable row level security;
alter table public.kd_votes enable row level security;

-- API 권한을 명시적으로 보장합니다.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.kd_vote_state to anon, authenticated;
grant select, insert, update, delete on public.kd_votes to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- 같은 이름의 정책이 있으면 안전하게 다시 만듭니다.
drop policy if exists "vote_state_read" on public.kd_vote_state;
drop policy if exists "vote_state_insert" on public.kd_vote_state;
drop policy if exists "vote_state_update" on public.kd_vote_state;
drop policy if exists "votes_read" on public.kd_votes;
drop policy if exists "votes_insert" on public.kd_votes;
drop policy if exists "votes_update" on public.kd_votes;
drop policy if exists "votes_delete" on public.kd_votes;

create policy "vote_state_read" on public.kd_vote_state for select to anon, authenticated using (true);
create policy "vote_state_insert" on public.kd_vote_state for insert to anon, authenticated with check (true);
create policy "vote_state_update" on public.kd_vote_state for update to anon, authenticated using (true) with check (true);
create policy "votes_read" on public.kd_votes for select to anon, authenticated using (true);
create policy "votes_insert" on public.kd_votes for insert to anon, authenticated with check (true);
create policy "votes_update" on public.kd_votes for update to anon, authenticated using (true) with check (true);
create policy "votes_delete" on public.kd_votes for delete to anon, authenticated using (true);

-- Realtime 등록: 이미 등록된 경우는 그대로 둡니다.
do $$ begin
  alter publication supabase_realtime add table public.kd_vote_state;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.kd_votes;
exception when duplicate_object then null; end $$;
