-- 2026 경덕 ALL PLAY 행운권 V76.15
-- 기존 응모 테이블을 유지하면서 '명단 확정'과 '당첨 결과 영구 저장'을 추가합니다.
-- Supabase SQL Editor에서 1회 실행하세요.

create table if not exists public.kd_lucky_entries (
  student_id text primary key,
  student_name text not null,
  pin_hash text not null,
  prize_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kd_lucky_state (
  id integer primary key default 1 check (id=1),
  is_finalized boolean not null default false,
  finalized_at timestamptz
);
insert into public.kd_lucky_state(id,is_finalized) values(1,false)
on conflict (id) do nothing;

create table if not exists public.kd_lucky_winners (
  id bigint generated by default as identity primary key,
  prize_id text not null,
  draw_order integer not null,
  student_id text not null,
  student_name text not null,
  drawn_at timestamptz not null default now(),
  unique(prize_id, draw_order),
  unique(prize_id, student_id)
);

alter table public.kd_lucky_entries enable row level security;
alter table public.kd_lucky_state enable row level security;
alter table public.kd_lucky_winners enable row level security;

drop policy if exists "lucky anon read" on public.kd_lucky_entries;
drop policy if exists "lucky anon insert" on public.kd_lucky_entries;
drop policy if exists "lucky anon update" on public.kd_lucky_entries;
drop policy if exists "lucky anon delete" on public.kd_lucky_entries;
create policy "lucky anon read" on public.kd_lucky_entries for select to anon using (true);
create policy "lucky anon insert" on public.kd_lucky_entries for insert to anon with check (true);
create policy "lucky anon update" on public.kd_lucky_entries for update to anon using (true) with check (true);
create policy "lucky anon delete" on public.kd_lucky_entries for delete to anon using (true);

drop policy if exists "lucky state anon read" on public.kd_lucky_state;
drop policy if exists "lucky state anon write" on public.kd_lucky_state;
create policy "lucky state anon read" on public.kd_lucky_state for select to anon using (true);
create policy "lucky state anon write" on public.kd_lucky_state for all to anon using (true) with check (true);

drop policy if exists "lucky winners anon read" on public.kd_lucky_winners;
drop policy if exists "lucky winners anon insert" on public.kd_lucky_winners;
create policy "lucky winners anon read" on public.kd_lucky_winners for select to anon using (true);
create policy "lucky winners anon insert" on public.kd_lucky_winners for insert to anon with check (true);
