-- V77 학급 퍼포먼스 조회수
create table if not exists public.kd_performance_views (
  id bigint generated by default as identity primary key,
  class_key text not null,
  viewer_key text not null,
  view_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique(class_key, viewer_key, view_date)
);
alter table public.kd_performance_views enable row level security;
drop policy if exists "public read performance views" on public.kd_performance_views;
create policy "public read performance views" on public.kd_performance_views for select to anon using (true);
drop policy if exists "public insert performance views" on public.kd_performance_views;
create policy "public insert performance views" on public.kd_performance_views for insert to anon with check (true);
