-- V85 공용 Q&A + 관리자 답변
create table if not exists public.kd_qna (
  id bigint generated by default as identity primary key,
  class_name text not null check (char_length(class_name) <= 10),
  name text not null check (char_length(name) <= 20),
  category text not null default '일반' check (char_length(category) <= 30),
  question text not null check (char_length(question) <= 300),
  answer text default '' check (char_length(answer) <= 500),
  status text not null default 'pending' check (status in ('pending','answered')),
  created_at timestamptz not null default now(),
  answered_at timestamptz
);
alter table public.kd_qna enable row level security;
drop policy if exists "qna public insert" on public.kd_qna;
create policy "qna public insert" on public.kd_qna for insert to anon, authenticated with check (status='pending' and coalesce(answer,'')='');
drop policy if exists "qna public read" on public.kd_qna;
create policy "qna public read" on public.kd_qna for select to anon, authenticated using (true);
-- 현재 V85 관리자 로그인은 프런트엔드 방식이므로 관리자 답변/삭제를 위해 anon update/delete가 필요합니다.
-- 강한 보안이 필요하면 추후 Supabase Auth + 관리자 전용 RLS로 전환하세요.
drop policy if exists "qna public update" on public.kd_qna;
create policy "qna public update" on public.kd_qna for update to anon, authenticated using (true) with check (true);
drop policy if exists "qna public delete" on public.kd_qna;
create policy "qna public delete" on public.kd_qna for delete to anon, authenticated using (true);
do $$ begin
  alter publication supabase_realtime add table public.kd_qna;
exception when duplicate_object then null;
end $$;
