-- V74 신청곡 공용 저장 / 관리자 승인
create table if not exists public.kd_song_requests (
  id bigint generated by default as identity primary key,
  class_name text not null check (char_length(class_name) <= 10),
  name text not null check (char_length(name) <= 20),
  title text not null check (char_length(title) <= 100),
  message text default '' check (char_length(message) <= 300),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.kd_song_requests enable row level security;

drop policy if exists "song public insert" on public.kd_song_requests;
create policy "song public insert" on public.kd_song_requests for insert to anon, authenticated with check (status = 'pending');

drop policy if exists "song public read" on public.kd_song_requests;
create policy "song public read" on public.kd_song_requests for select to anon, authenticated using (true);

-- 현재 웹앱은 별도 관리자 인증 서버가 없으므로 관리자 화면의 승인/삭제를 위해 anon update/delete를 허용합니다.
-- 관리자 비밀번호가 프런트엔드에 있는 구조이므로 보안 경계로 사용할 수 없습니다.
drop policy if exists "song public update" on public.kd_song_requests;
create policy "song public update" on public.kd_song_requests for update to anon, authenticated using (true) with check (true);

drop policy if exists "song public delete" on public.kd_song_requests;
create policy "song public delete" on public.kd_song_requests for delete to anon, authenticated using (true);

alter publication supabase_realtime add table public.kd_song_requests;
