-- Supabase SQL Editor에서 한 번 실행하세요.
create table if not exists public.qna (
  id bigint generated by default as identity primary key,
  student_no text not null,
  student_name text not null,
  question text not null,
  answer text default '',
  created_at timestamptz default now()
);

alter table public.qna enable row level security;

drop policy if exists "qna public read" on public.qna;
create policy "qna public read"
on public.qna for select
to anon
using (true);

drop policy if exists "qna public insert" on public.qna;
create policy "qna public insert"
on public.qna for insert
to anon
with check (
  char_length(student_no) between 1 and 8
  and char_length(student_name) between 1 and 10
  and char_length(question) between 1 and 500
);

-- 웹앱 교직원 비밀번호는 프론트엔드에 노출될 수 있으므로,
-- 아래 UPDATE 정책은 간편 운영용입니다.
-- 실제 보안을 강화하려면 Supabase Auth 관리자 로그인을 붙이는 것을 권장합니다.
drop policy if exists "qna public update" on public.qna;
create policy "qna public update"
on public.qna for update
to anon
using (true)
with check (true);

alter publication supabase_realtime add table public.qna;
