-- 2026 경덕 ALL PLAY V61 교직원 실시간 투표
-- Supabase > SQL Editor에서 한 번만 실행하세요.

create table if not exists public.kd_vote_state (
  vote_type text primary key check (vote_type in ('performance','flag')),
  is_open boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.kd_vote_state(vote_type,is_open)
values ('performance',false),('flag',false)
on conflict (vote_type) do nothing;

create table if not exists public.kd_votes (
  id bigint generated by default as identity primary key,
  voter_name text not null,
  vote_type text not null check (vote_type in ('performance','flag')),
  grade integer not null check (grade between 1 and 3),
  class_no integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kd_votes_one_per_grade unique (voter_name, vote_type, grade)
);

alter table public.kd_vote_state enable row level security;
alter table public.kd_votes enable row level security;

-- 학교 행사 내부용 간편 정책: anon 사용자가 투표 상태/투표 데이터를 읽고 쓰도록 허용합니다.
-- 중복은 DB unique 제약으로 막습니다. 관리자 비밀번호는 웹앱 UI 진입용입니다.
do $$ begin
  create policy "vote_state_read" on public.kd_vote_state for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "vote_state_update" on public.kd_vote_state for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "votes_read" on public.kd_votes for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "votes_insert" on public.kd_votes for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "votes_update" on public.kd_votes for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "votes_delete" on public.kd_votes for delete to anon using (true);
exception when duplicate_object then null; end $$;

-- Realtime 반영
do $$ begin
  alter publication supabase_realtime add table public.kd_vote_state;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.kd_votes;
exception when duplicate_object then null; end $$;
